name: Moj Pierwszy Workflow

# 1. Kiedy akcja ma się uruchomić?
on: [push]

# 2. Co akcja ma zrobić?
jobs:
  przywitanie:
    # Na jakim systemie ma działać (np. najnowsze Ubuntu)
    runs-on: ubuntu-latest

    # Lista kroków do wykonania
    steps:
      - name: Sprawdzenie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Uruchomienie prostego skryptu
        run: echo "Cześć! GitHub Actions działa!"