name: Testy Pythona

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Pobierz kod z repozytorium
    - name: Pobranie kodu
      uses: actions/checkout@v4

    # 2. Skonfiguruj odpowiednią wersję Pythona
    - name: Ustawienie Pythona
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Możesz wpisać swoją wersję, np. '3.10', '3.12'

    # 3. Zainstaluj zależności (jeśli masz plik requirements.txt)
    - name: Instalacja zalezności
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest # Instalujemy pytest, jeśli nie ma go w requirements.txt

    # 4. Uruchom testy
    - name: Uruchomienie pytest
      run: |
        pytest
        
  other-things:
    runs-on: ubuntu-latest
    
    steps:
    - name: Nazwa systemu
      run: |
        uname -a
     
    - name: Ile miejsca na dysku
      run: |
        df -h